<a href="https://colab.research.google.com/github/akashsabale01/DSBDA_Lab/blob/main/Ass_No_6_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ass No 6 - Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.

In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt


In [4]:
df = pd.read_csv('/content/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
number = LabelEncoder()
df.SepalLengthCm = number.fit_transform(df.SepalLengthCm)
df.SepalWidthCm = number.fit_transform(df.SepalWidthCm)
df.PetalLengthCm = number.fit_transform(df.PetalLengthCm)
df.PetalWidthCm = number.fit_transform(df.PetalWidthCm)
df.Species = number.fit_transform(df.Species)

df


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1              8            14              4             1        0
1      2              6             9              4             1        0
2      3              4            11              3             1        0
3      4              3            10              5             1        0
4      5              7            15              4             1        0
..   ...            ...           ...            ...           ...      ...
145  146             24             9             28            19        2
146  147             20             4             26            15        2
147  148             22             9             28            16        2
148  149             19            13             30            19        2
149  150             16             9             27            14        2

[150 rows x 6 columns]

In [6]:
features = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm' , 'PetalWidthCm']]
target = df['Species']

In [7]:
model = GaussianNB()
model.fit(features,target)
# scenario for prediction: outlook = rainy(1),temp = cool(0), Humidity = high(0), wind= strong(0)
scenario = [[1,0,0,0]]
print("Model prediction",model.predict(scenario))
print("Probability prediction",model.predict_proba(scenario))

Model prediction [0]
Probability prediction [[9.99999905e-01 9.54750178e-08 6.88554665e-17]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"


In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

print("\nConfusion Matrix\n", confusion_matrix(target,model.predict(features)))
print("\nClassification report\n", classification_report(target,model.predict(features)))
print("\nAccuracy score\n", accuracy_score(target,model.predict(features)))


Confusion Matrix
 [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]

Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150


Accuracy score
 0.96
